# DataSource Config
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  rabbitmq:
    port: 5672
    host: localhost
    username: xxx
    password: xxx
    listener:
      simple:
        prefetch: 2 # 设置qos最大缓存数，预接受10个消息到缓存中
        concurrency: 2 # 处理线程数，可以理解为同一时间处理多少个消息
        max-concurrency: 4
  mail:
    # 发送者邮箱
    username: xxx
    #申请到的授权码
    password: xxx
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 端口号465或587
    port: 465
    protocol: smtps
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
          debug: true
          ssl: true
  # application.yml
  ai:
    dashscope:
      api-key: xxxxxxxxx
      # 连接超时配置
      connect-timeout: 30
      read-timeout: 60
      write-timeout: 60
    chat:
      options:
        model: qwen-plus
        enable_search: true
  web:
    reactive:
      client:
        # HTTP客户端连接池配置
        connection-pool:
          max-connections: 100
          max-idle-time: 30
          # 连接超时配置
          connect-timeout: 30000
          response-timeout: 60000
  application:
    name: gh_ai_analysis
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: xxxx
    password: xxxxx
    url: jdbc:mysql://localhost:3306/gh_ai_analysis
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      lettuce:
        pool:
          max-idle: 16
          max-active: 32
          min-idle: 8

alipay:
  protocol: https
  # 应用ID，标识你的应用
  appId: 9021000160607590
  # 应用私钥，用于签名请求
  merchantPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCDQxRDpdG+E/xtDD5EZ5viKmdBkc7O4156xZZyY0K8IjqmNPVNTUDYuCpT4fbrGtUX0+lMy3T0XZe7MfPwxk0pK0ha1J5OKc6j0n3aPRnwFqeUuVShdRRh4cKi2qxFXCQbB8q5OvQppmbBqRz2zYZHlCP19spwsJ5CMoMljdZrZBgS4XiGAKtDXtGOk/eJDmsJ+c/cFDCnvKN2LKrdVvQ/d817pB3oTsNUlzGxu9IRgb0hph27RuBw1Bf2B4S3JvHrZPkShi6q7X5RezVL0iICj82UNWz9yVBQSZmKhtx6jqTPVQJKGba0ovBwM3tgaQx8BpZO/2z3JhdOVMcI64dpAgMBAAECggEABxcUfSLz1WSW+fzzUBaYoPrRYQVTOnGlpNQPcFZUQH1I1bl+lpJZslsgTi+iesiUQhk8PN2wj5KOo5nrJ1JO0K551g4uDuLLOqYgDi3GvOU8YBgyrhX45+Cd9tYBAC4d9SfSl3bLwYQvgL51xg8L9cnWt26BON0Rb1nzI5ApyNsnBX0m6cBjxXDQbPLWQBQaoeHCoP00/faKwKqIkPVBAiU91wEftvHAmz08wOZwJh3xeGI+I1D4t/wMcEoT79s7gahGprXlhINdIXOu92Hj4mZxzUCgl6ns/qGnGPyqSixUwbxPz5VHA8kKUmSqrEqQbKagYc3fDzBpbW7v1/6MAQKBgQDhzEnNLxVlxjlA8oU+ShYdeC6wWrjgiKY7bjxTO89gatMPITqBtDRtLIklejU0NjN1ZzlMTFwymcfUUg7ZO7JSgalSdmQCDn5uHlTVAAWoLwpfsBo293/JxVmle0On6dy8bMc77NIbpZXGyEu6Hru1N9L+nK/45WZr8jEPeh6TiQKBgQCU0bd1nYzcWmR9Y/5LHT6wEMCsLcVUhTthb2ckLbEW6U7VL/cnVddCainRV2dM0nn9N/ywoi5dWuXC5JW5hDGPJlmRRwzAim+F3zQ7DGM8eyB2Ayva4oaDUgzBP0w5kRV+EzfATCJkT427xqP9WsD1jSpC6Rucx3IaA+MeUwn84QKBgAqXTHblWHmXnKPhPEK5suPa+UWoW7eccT+kYgv9aDK7j/7LrjTbQQJF7oDlhI1YZX2CQ/vCMSjmcasR1kR2Ol0IW+rURsiZ6XA81/nNsHY9Dp2CYxhk74eFTDko2PmNTJ9B8u5qo0hMsgPK7VJjkqZjYfAzZUWlbPJvP8HcFocRAoGAAdZI5nnIaFvxS571X6X/xRqf1kBGZFG0tvIyGr85pWfB4l3SNjkYDCjVVVE35Dng6aBMTT3jRqG9nldGBeE832CA0ItI/AN5dvSXZ3cyrmdysiI941jSgkJ8B9KpNTi2RDUmhggqkIRu4neERLdfFGjmsabBAYFwxiNwJUqvH+ECgYAyMhBh45KbBPyqfo5K4qnIKW9iVWGuGDKCMroQztM+8UUxqSoVDOurpGu0NaXG+oy90FWRXyvRkeaPwYEWG1GCZdat9qZktCxmP8NU8phX5u+8eZZx1OrAQYObNSI+dhcpN+oEDnud97zlydP1wU/5rQJQ9P/FzjHCHN/CLLBLIA==
  # 应用公钥，用于验证支付宝的响应
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnhCOA0j2sa6Ur9lfgaM7UN8Z5BesiyI/U7Wau9TFTf/LTfsiCtFkOanUYHJKNsYc9wiAHyzTRRgh05z+LIOIpha2cPOz7HeOjIaO79V1ZZBY+/SGzTARSaWrvpXtAB6Mtggk8ibPdYX2LZZoIvJpUocqP3xgd5+jp9Hw8L3FPiJ/8W+xGTBNh+66L1gx/VHSYWk9BgEQJZCqeJrWu79ONEZ8C3kS7hdPfqupSFY0xmJiLgML0l6oWa74DWRmvM/ywEYs4d3bYq3jFLFJJcWk0pMEskE/ygLhyc5CnPrX+6L4qeipIGXkzG8irt/MuHG+k6lqus5rgpZKvjeQXTaYqQIDAQAB
  # 支付通知的回调地址，支付宝会在支付完成后通知这个地址
  notifyUrl: http://119.91.68.39:8123/api/alipay/notify
  # 页面跳转地址，支付完成后跳转到此URL
  returnUrl: http://119.91.68.39:3000/user/center
#  returnUrl: https://www.baidu.com
  # 签名类型，通常为RSA2
  signType: RSA2
  # 字符编码，通常为utf-8
  charset: utf-8
  # 支付宝网关地址，用于发送请求
  gatewayHost: https://openapi-sandbox.dl.alipaydev.com/gateway.do


# searchApi
search-api:
  api-key: xxx

server:
  port: 8123
  servlet:
    context-path: /api
  reactive:
    session:
      timeout: 600m
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

aliyun:
  dypnsapi:
    access-key-id: xxx
    access-key-secret: xx
  green:
    accessKeyId: xx
    accessSecret: xx
  oss:
    accessKey: xx
    secretKey: xx
    bucketName: ai-xx-jgh
    endpoint: https://oss-xx-shenzhen.aliyuncs.com
    region: cn-xx

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.jgh.aianalysis.controller
knife4j:
  enable: false
  setting:
    language: zh_cn

# application.yml
dubbo:
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848?username=nacos&password=nacos
    # This will enable application-level service discovery only (the recommended service discovery method for Dubbo3).
    # For users upgrading from Dubbo2.x, please set the value to 'all' for smooth migration.
    register-mode: instance
  protocol:
    name: tri
    port: 50051
  application:
    name: dubbo-springboot-provider
    logger: slf4j
